[site]
title = "Yi Sun"
description = "Yi Sun is an undergraduate researcher working on computer architecture, AI accelerators, and hardware-software co-design."
url = "https://yisun219.github.io"
favicon = "/favicon.svg"
last_updated = "May 30, 2026"


[author]
name = "Yi Sun (孙燚)"
title = "Undergraduate Researcher"
institution = "South China University of Technology"
avatar = "/yicun.JPG"

[social]
# Contact information (leave blank or delete to hide)

email = "ecesunyi@gmail.com"
location = "Guangzhou, China"
location_url = "https://www.google.com/maps/place/Guangzhou"
location_details = [
  "Guangzhou, China"
]

github = "https://github.com/yisun219"
linkedin = "https://www.linkedin.com/in/yi-sun-8754b7389/"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Honors & Awards"
type = "page"
target = "awards"
href = "/awards"
